### ISSUE TITLE
Commands only work if bot has admin permissions

### ISSUE THREAD

**Issue by sam-kirby** [chamburr/wyvor#2]
**Describe the bug**
The bot will not respond to commands unless it has Administrator permissions. At one point I gave the bot and everybody every permission except admin and it still would not respond to messages on a channel with no overrides.

**Steps to reproduce**
1. Add bot to server without giving admin permissions
2. Send message in a channel the bot has permission to view, send messages and embeds in
3. Wait for a reply that will never come?

**Expected behavior**
Bot replies - it does not **need** Administrator permissions

**Client information:**
N/A

**Additional context**
https://github.com/chamburr/wyvor/blob/8c987a4097e3a9eff1bc3a600326a71324f3cf80/bot/utils/utils.go#L166-L172

The fall through behaviour of this function should be `return true` if I'm reading it correctly; regardless, it seems impossible for this function to return true if the bot is not an admin.

**Comment by chamburr** [comment]
Seems like it

**Comment by chamburr** [comment]
Fixed in 2491e4665a986be8b1850b1840f528dcc0cde8fb, thanks
